# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
#   - main

# pool:
#   vmImage: ubuntu-latest

# steps:
#   - script: echo Hello, world!
#     displayName: 'Run a one-line script'

#   - script: |
#       echo Add other tasks to build, test, and deploy your project.
#       echo See https://aka.ms/yaml
#     displayName: 'Run a multi-line script'

#   - script: |
#       # Add your deployment commands here
#       # For example, deploying to a remote server or a cloud platform
#       echo Deploying your code...
#     displayName: 'Deploy'

trigger:
  branches:
    include:
      - main  # Specify the branch you want to trigger the pipeline

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self   # Fetches the source code of the repository

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Restoring dependencies...
    cd ../Online-Car-System
    dotnet restore
  displayName: 'Restore Dependencies'

- script: |
    echo Building your project...
    cd ../Online-Car-System
    dotnet build --configuration Release
  displayName: 'Build'