# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfig: 'release'

steps:
- script: dotnet build --configuration $(buildConfig)
  displayName: 'dotnet build $(buildConfig)'
